image: nixos/nix

build:
  stage: build
  script: nix-shell --run 'clojure -m prism-break.tasks.build-release'
  artifacts:
    paths:
    - out

pages:
  stage: deploy
  script: mv out public
  artifacts:
    paths:
    - public
  only:
  - master
